# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Thinking@Scale
tagline:          ' Yan Qi '
description:      'Thinking@Scale'
url:              https://yan-qi.github.io
baseurl:          '/'
paginate:         5

# Custom vars
version:          1.0.0
  
pages_list:       
  About: '/about'
  Feed: ' /atom.xml'