# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Yan Qi
tagline:          ' Brave New World '
description:      'Brave New World'
url:              http://yan-qi.github.io
baseurl:          '/'
paginate:         5

# Custom vars
version:          1.0.0
  
pages_list:       
  About: '/about'
  Feed: '/atom.xml'