# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Think@Scale
tagline:          ' Yan Qi '
description:      'Think@Scale'
url:              http://www.thinkscale.com
baseurl:          '/'
paginate:         5

# Custom vars
version:          1.0.0
  
pages_list:       
  About: '/about'
  Feed: '/atom.xml'